
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jbrod.webmanager_server.analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLASS_TYPE_MEN = 16;
  public static final int PRM_VAL_ID = 2;
  public static final int ATR_TYPE_TXT = 32;
  public static final int ATR_VAL_INTG = 11;
  public static final int PARAMETRO_CL = 29;
  public static final int ATR_VAL_COLH = 9;
  public static final int ACC_ADD_WBST = 41;
  public static final int PARAM_TYPE_FMD = 25;
  public static final int ACC_MOD_PAGW = 45;
  public static final int ATR_TYPE_ALT = 36;
  public static final int ATR_VAL_TEXT = 10;
  public static final int ACC_ADD_PAGW = 43;
  public static final int ATR_TYPE_ALN = 34;
  public static final int ATRIBUTO_CL = 38;
  public static final int PARAM_TYPE_FCR = 24;
  public static final int ETIQUETAS_CL = 51;
  public static final int ATRIBUTOS_CL = 31;
  public static final int ETIQUETAS_OP = 50;
  public static final int ACC_MOD_COMP = 48;
  public static final int PARAM_TYPE_USM = 26;
  public static final int ATRIBUTOS_OP = 30;
  public static final int ACC_ADD_COMP = 46;
  public static final int PRM_VAL_FCH = 3;
  public static final int ACC_DEL_WBST = 42;
  public static final int ATR_VAL_CENT = 5;
  public static final int PARAM_TYPE_USC = 23;
  public static final int EOF = 0;
  public static final int ACCION_CL = 49;
  public static final int error = 1;
  public static final int ACCIONES_CL = 40;
  public static final int ACCIONES_OP = 39;
  public static final int ACC_DEL_PAGW = 44;
  public static final int PARAM_TYPE_ID = 19;
  public static final int PARAM_TYPE_TIT = 20;
  public static final int PARAM_TYPE_CLS = 28;
  public static final int ATR_VAL_IZQD = 6;
  public static final int ATR_TYPE_ANC = 37;
  public static final int ATR_TYPE_ORI = 35;
  public static final int PRM_VAL_TIT = 4;
  public static final int ATR_VAL_DERE = 7;
  public static final int ACC_DEL_COMP = 47;
  public static final int CLASS_TYPE_VID = 15;
  public static final int PARAM_TYPE_SIT = 21;
  public static final int CLASS_TYPE_TIT = 12;
  public static final int ATR_VAL_JUST = 8;
  public static final int PARAM_TYPE_PAG = 27;
  public static final int ETIQUETA = 52;
  public static final int PARAMETROS_CL = 18;
  public static final int PARAM_TYPE_PAD = 22;
  public static final int CLASS_TYPE_PAR = 13;
  public static final int PARAMETROS_OP = 17;
  public static final int CLASS_TYPE_IMG = 14;
  public static final int ATR_TYPE_CLR = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRM_VAL_ID",
  "PRM_VAL_FCH",
  "PRM_VAL_TIT",
  "ATR_VAL_CENT",
  "ATR_VAL_IZQD",
  "ATR_VAL_DERE",
  "ATR_VAL_JUST",
  "ATR_VAL_COLH",
  "ATR_VAL_TEXT",
  "ATR_VAL_INTG",
  "CLASS_TYPE_TIT",
  "CLASS_TYPE_PAR",
  "CLASS_TYPE_IMG",
  "CLASS_TYPE_VID",
  "CLASS_TYPE_MEN",
  "PARAMETROS_OP",
  "PARAMETROS_CL",
  "PARAM_TYPE_ID",
  "PARAM_TYPE_TIT",
  "PARAM_TYPE_SIT",
  "PARAM_TYPE_PAD",
  "PARAM_TYPE_USC",
  "PARAM_TYPE_FCR",
  "PARAM_TYPE_FMD",
  "PARAM_TYPE_USM",
  "PARAM_TYPE_PAG",
  "PARAM_TYPE_CLS",
  "PARAMETRO_CL",
  "ATRIBUTOS_OP",
  "ATRIBUTOS_CL",
  "ATR_TYPE_TXT",
  "ATR_TYPE_CLR",
  "ATR_TYPE_ALN",
  "ATR_TYPE_ORI",
  "ATR_TYPE_ALT",
  "ATR_TYPE_ANC",
  "ATRIBUTO_CL",
  "ACCIONES_OP",
  "ACCIONES_CL",
  "ACC_ADD_WBST",
  "ACC_DEL_WBST",
  "ACC_ADD_PAGW",
  "ACC_DEL_PAGW",
  "ACC_MOD_PAGW",
  "ACC_ADD_COMP",
  "ACC_DEL_COMP",
  "ACC_MOD_COMP",
  "ACCION_CL",
  "ETIQUETAS_OP",
  "ETIQUETAS_CL",
  "ETIQUETA"
  };
}

