
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jbrod.webmanager_client.app.stats;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAGINAS_POPULARES = 5;
  public static final int IMAGEN = 9;
  public static final int COMPONENTE_TYPE = 13;
  public static final int CONSULTAR = 2;
  public static final int TODOS = 12;
  public static final int VIDEO = 10;
  public static final int MENU = 11;
  public static final int ID = 21;
  public static final int COMILLAS = 14;
  public static final int COMPONENTE = 6;
  public static final int SEPARADOR = 20;
  public static final int COMMA = 15;
  public static final int PARRAFO = 8;
  public static final int FININSTR = 16;
  public static final int EOF = 0;
  public static final int VAL_CL = 18;
  public static final int VAL_OP = 17;
  public static final int VISITAS_PAGINA = 4;
  public static final int error = 1;
  public static final int VISITAS_SITIO = 3;
  public static final int TITULO = 7;
  public static final int INICIO = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONSULTAR",
  "VISITAS_SITIO",
  "VISITAS_PAGINA",
  "PAGINAS_POPULARES",
  "COMPONENTE",
  "TITULO",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "TODOS",
  "COMPONENTE_TYPE",
  "COMILLAS",
  "COMMA",
  "FININSTR",
  "VAL_OP",
  "VAL_CL",
  "INICIO",
  "SEPARADOR",
  "ID"
  };
}

